name = "asigns-worker"
main = "src/index.ts"
compatibility_date = "2024-09-01"

[ai]
binding = "AI"

[[d1_databases]]
binding = "DB"
database_name = "asigns-db"
database_id = "e9f9ea96-0e1e-4661-b4c7-e537bb3151a5"

[vars]
ALLOWED_ORIGIN = "https://asignsinc.com"
NOTIFY_EMAIL = "asigns025@gmail.com"
